package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;


public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager() {
        manager = Managers.getDefault();
    }

    @Test
    public void testAddTask() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().getFirst();
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId() {
        Task task = new Task(42, "Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().getFirst();
        assertEquals(1, addedTask.getId(), "predefined task id should be replaced");
        assertEquals(1, task.getId(), "predefined task id should be replaced");
    }

    @Test
    public void testAddTaskWithAndWithoutId() {
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
        assertEquals(2, task1.getId(), "task predefined id should be changed");
    }

    @Test
    public void checkTaskChangedAfterAddTask() {
        int id = 2;
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task(id, name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertNotEquals(task1after.getId(), id);
        assertEquals(task1after.getDescription(), description);
        assertEquals(task1after.getStatus(), status);
        assertEquals(task1after.getName(), name);
    }

    @Test
    public void checkTaskAddedInHistory() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        manager.getTask(1);
        assertTrue(manager.getHistory().contains(task), "task should be added in history");
    }

    @Test
    public void checkTaskRemovedFromHistory() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        manager.getTask(1);
        assertTrue(manager.getHistory().contains(task), "task should be added in history");
        manager.deleteTask(1);
        assertEquals(0, manager.getTasks().size(), "task should be removed");
        assertFalse(manager.getHistory().contains(task), "task should be removed from history");
    }

    @Test
    public void checkHistoryLimitIsOver10() {
        for (int i = 0; i < 11; i++) {
            Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
            manager.addNewTask(task);
            assertEquals(i + 1, manager.getTasks().size(), "task should be added");
            manager.getTask(i + 1);
            assertEquals(i + 1, manager.getHistory().size(), "task should be added in history");
        }
    }

    @Test
    public void checkAllTypesOfTasks() {
        for (int i = 1; i <= 3; i++) {
            Task task = new Task("Test " + i, "Testing task " + i, TaskStatus.NEW);
            manager.addNewTask(task);
        }
        Epic epic = new Epic("Epic 1", "Testing epic 1");
        manager.addNewEpic(epic);
        assertEquals(TaskStatus.NEW, manager.getEpic(epic.getId()).getStatus(), "Epic status should be NEW");
        for (int i = 1; i <= 3; i++) {
            Subtask subtask = new Subtask("Test " + i, "Testing task " + i, TaskStatus.NEW, epic.getId());
            manager.addNewSubtask(subtask);
            epic.addSubtaskId(subtask.getId());
        }
        assertEquals(3, manager.getTasks().size(), "3 tasks should be added");
        assertEquals(1, manager.getEpics().size(), "1 epic should be added");
        assertEquals(3, manager.getSubtasks().size(), "3 subtasks should be added");
        assertEquals(TaskStatus.NEW, manager.getEpic(epic.getId()).getStatus(), "Epic status should be NEW");
        manager.updateSubtask(new Subtask(5, "New", "Testing new", TaskStatus.IN_PROGRESS, epic.getId()));
        assertEquals(TaskStatus.IN_PROGRESS, manager.getSubtask(5).getStatus(), "Subtask status should be IN_PROGRESS");
        assertEquals(TaskStatus.IN_PROGRESS, manager.getEpic(epic.getId()).getStatus(), "Epic status should be IN_PROGRESS");
        manager.updateTask(new Task(2, "New 2", "Testing new 2", TaskStatus.DONE));
        assertEquals(TaskStatus.DONE, manager.getTask(2).getStatus(), "Task status should be DONE");
        manager.updateEpic(new Epic(epic.getId(), "Absolutely new epic", "Description"));
        manager.deleteTask(1);
        assertEquals(2, manager.getTasks().size(), "1 tasks should be deleted, 2 remain");
        manager.deleteTasks();
        assertEquals(0, manager.getTasks().size(), "All tasks should be deleted");
        manager.deleteSubtask(5);
        assertEquals(2, manager.getSubtasks().size(), "1 subtasks should be deleted, 2 remain");
        assertEquals(2, manager.getEpicSubtasks(epic.getId()).size(), "1 subtasks should be deleted, 2 remain");
        assertEquals(TaskStatus.NEW, manager.getEpic(epic.getId()).getStatus(), "Epic status should be NEW");
        manager.deleteSubtasks();
        assertEquals(0, manager.getSubtasks().size(), "All subtasks should be deleted");
        assertEquals(0, manager.getEpicSubtasks(epic.getId()).size(), "All subtasks should be deleted");
        assertEquals(TaskStatus.NEW, manager.getEpic(epic.getId()).getStatus(), "Epic status should be NEW");
        for (int i = 1; i <= 3; i++) {
            Subtask subtask = new Subtask("Test " + i, "Testing task " + i, TaskStatus.NEW, epic.getId());
            manager.addNewSubtask(subtask);
            epic.addSubtaskId(subtask.getId());
        }
        assertEquals(3, manager.getSubtasks().size(), "3 subtasks should be added");
        manager.deleteEpic(epic.getId());
        assertEquals(0, manager.getEpics().size(), "All epics should be deleted");
        assertEquals(0, manager.getSubtasks().size(), "All subtasks should be deleted");
        for (int i = 1; i <= 3; i++) {
            Epic epic1 = new Epic("Epic " + i, "Testing epic " + i);
            manager.addNewEpic(epic1);
            for (int j = 1; j <= 3; j++) {
                Subtask subtask = new Subtask("Test " + j, "Testing task " + j, TaskStatus.NEW, epic1.getId());
                manager.addNewSubtask(subtask);
                epic.addSubtaskId(subtask.getId());
            }
        }
        assertEquals(3, manager.getEpics().size(), "3 epics should be added");
        assertEquals(9, manager.getSubtasks().size(), "9 subtasks should be added");
        manager.deleteEpics();
        assertEquals(0, manager.getEpics().size(), "All epics should be deleted");
        assertEquals(0, manager.getSubtasks().size(), "All subtasks should be deleted");
    }

    @Test
    public void checkUpdateNonExistentTasks() {
        assertDoesNotThrow(() -> manager.updateTask(new Task(5, "Task", "Task", TaskStatus.NEW)), "Should work correct");
        assertDoesNotThrow(() -> manager.updateSubtask(new Subtask(1, "Subtask", "Subtask", TaskStatus.NEW, 3)), "Should work correct");
        Subtask subtask = new Subtask("Subtask", "Subtask", TaskStatus.NEW, 1);
        assertNull(manager.addNewSubtask(subtask), "Should return null, epic doesn't exist");
        Epic epic = new Epic("Epic", "Epic");
        manager.addNewEpic(epic);
        manager.addNewSubtask(subtask);
        Subtask subtask1 = new Subtask("Subtask", "Subtask", TaskStatus.NEW, 3);
        assertDoesNotThrow(() -> manager.updateSubtask(subtask1), "Should work correct");

    }
}
